spring.application.name=catalog
server.port=9000

spring.datasource.url=jdbc:postgresql://localhost:5432/catalog_db
spring.datasource.username=${DB_USER:cs_user}
spring.datasource.password=${DB_PASS:change-me}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect